name: CI Workflow

on:
  push:
    branches:
      - master  
jobs:
  build:
    runs-on: self-hosted
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v2
   
      - name: Upload to S3
        run: |
          aws s3 cp ./images.png s3://vinsawsbucket/images.png
       
      - name: Connect to PostgreSQL RDS and create table
        run: |
          psql -h vinawsdatabase15version.c9k0gky0kmco.us-east-1.rds.amazonaws.com -U postgres -d mydatabase -c "CREATE TABLE IF NOT EXISTS fruits (id SERIAL PRIMARY KEY, name VARCHAR(50), color VARCHAR(20), quantity INT);"
        env:
          PGPASSWORD: ${{ secrets.RDS_PASSWORD }}  # Store your RDS password in GitHub Secrets
